name: insiders-test-case
services:
  node:
    container_name: insiders-node
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
      - redis
    command: sh -c "npm install  && npm run build && npm run migration:up && npm run prisma:seed && npm run start:dev"

  postgres:
    container_name: insiders-postgres
    image: postgres:16.3
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  postgres_data: {}
  redis-data: