name: insiders-test-case
services:
  node:
    container_name: insiders-node
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    command: sh -c "npm install  && npm run build && npm run migration:up&& npm run seed:up && npm run start:dev"

  postgres:
    container_name: insiders-postgres
    image: postgres:16.3
    env_file:
      - .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    entrypoint: >
      sh -c "chmod +x /docker-entrypoint-initdb.d/init-db.sh && exec docker-entrypoint.sh postgres"
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}